### ISSUE TITLE
"Sample" object "id" vs "inventory_id"

### ISSUE THREAD

**Issue by mosely1** [conflabs/wcia-lab-result-schema#1]
It has been proposed that the `WCIA Lab Result Schema -> sample` object be described as "An object containing properties associated with the sample transfer." This is taken to mean that any properties coming from the associated `WCIA Transfer Schema -> inventory_transfer_item` object is acceptable in the `WCIA Lab Result Schema -> sample` object.

This is desirable because numerous fields from the `inventory_transfer_item` such as `unit_weight`, `unit_weight_uom`, and `sample_source_id` are often necessary in the `WCIA Lab Result Schema -> sample` object.

**Proposal:** change the property name of `WCIA Lab Result Schema -> sample -> id` to `WCIA Lab Result Schema -> sample -> inventory_id` to match the property name of the corresponding `WCIA Transfer Schema -> inventory_transfer_item -> inventory_id`.

**Comment by bobbyahines** [comment]
Implemented.
